### ISSUE TITLE
test issue for all-contributors

### ISSUE THREAD

**Issue by shawnrhoads** [neuroimaging-cookbook/neuroimaging-cookbook.github.io#33]
testing all-contributors bot

**Comment by shawnrhoads** [comment]
@all-contributors init

**Comment by shawnrhoads** [comment]
all-contributors check

**Comment by shawnrhoads** [comment]
@all-contributors check

**Comment by shawnrhoads** [comment]
all-contributors add @shawnrhoads for code, ideas

**Comment by scovitz** [comment]
@all-contributors please add @shawnrhoads for code

**Comment by shawnrhoads** [comment]
@all-contributors check

**Comment by shawnrhoads** [comment]
@all-contributors add @shawnrhoads for ideas

**Comment by shawnrhoads** [comment]
@all-contributors check

**Comment by scovitz** [comment]
@all-contributors fetch

**Comment by scovitz** [comment]
@all-contributors please add @scovitz for design
