### ISSUE TITLE
Create a "Contributors" page

### ISSUE THREAD

**Issue by shawnrhoads** [neuroimaging-cookbook/neuroimaging-cookbook.github.io#5]
We will need to create a page to recognize everyone's contributions. Maybe using the [all-contributors](https://allcontributors.org/) specification, and/or possibly adding automation (add whoever submits a pull-request to this list)

**Comment by scovitz** [comment]
@all-contributors please add @scovitz for code
@all-contributors please add @shawnrhoads for code

**Comment by scovitz** [comment]
@all-contributors please add @shawnrhoads for code

**Comment by scovitz** [comment]
@all-contributors please add @scovitz for code

**Comment by scovitz** [comment]
@all-contributors please add @scovitz for code

**Comment by scovitz** [comment]
@all-contributors please add @scovitz for bug

**Comment by shawnrhoads** [comment]
Could be cool to use the [text file generated from this](https://github.com/neuroimaging-cookbook/neuroimaging-cookbook.github.io/blob/main/.all-contributorsrc) to create a page for the website!
